### ISSUE TITLE
scheduler_node: publish schedulable resources on a latched topic

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/concert_scheduling#8]
cross-reference: utexas-bwi/rocon_scheduler_requests#9

The likely solution involves publishing a new message whenever the resource_pool changes.

I am considering **/schedulable_resources** or **/schedulable_rocon_resources** for the default topic name. The first one seems better.

There is a use case for including the request `priority` of `ALLOCATED` resources. See [this earlier discussion](https://github.com/utexas-bwi/rocon_scheduler_requests/issues/9#issuecomment-35409419).

**Comment by stonier** [comment]
Sorry for the latency Jack, got tied up elsewhere. 

This topic would include all resources right, allocated or otherwise?

I'm not sure about the naming of schedulable_resources. That would seem to imply that it does not include any allocated resources. However as far as I understand, any allocated resources could be pre-empted and reallocated (i.e. rescheduled) if the incoming priority is higher.

**Comment by stonier** [comment]
I have the teleop service pipeline almost setup - turtlesim, turtle_concert/teleop robot app, qt teleop interaction. All it needs now is proper scheduling around which I'm hacking right now. Shall we take this simple scheduler for a spin?

**Comment by jack-oquin** [comment]
Yes. 

All it lacks right now is a subscription to the list of clients published by the conductor and publishing the contents of the resource pool. I'll try to add that tomorrow. 

> This topic would include all resources right, allocated or otherwise?

Yes. "Schedulable" seems somewhat confusing. I mean it in the sense of resources subject to scheduling. Maybe it would be clearer to label it as the "scheduler resource pool". I suppose there can be other ROCON resources not subject to the scheduler, but this would include all that are, whether currently available, allocated or missing.

**Comment by stonier** [comment]
:+1: `scheduler_resource_pool` sounds fine. `known_resources` would also work - that matches the msg name that would be getting published.

**Comment by jack-oquin** [comment]
I think I'll just call it `resource_pool`. Within the concert namespace, that should be clear enough.

**Comment by jack-oquin** [comment]
I am not sure what the `uninvited_clients` represent. 

Should they be added to the resource pool, also?

**Comment by stonier** [comment]
resource_pool sounds fine.

On 11 Mar 2014 10:35, "jack-oquin" notifications@github.com wrote:

> I am not sure what the uninvited_clients represent.

They are concert clients on the lan that might be busy for another concert
or idle but not yet pulled in for this concert.
The idea is that some use cases may permit clients to be shared across
multiple concerts (each lab office in a building running a concert but
sharing building robots to do tasks.

In this case the scheduler would be free to invite and make use of that
resource and then free it for other concerts when its job is done.

We are currently not availing ourselves of this feature yet. It is dubious
whether the concept can really be practical over lans only since there are
usually many lans in a building.

There are some small cases where it may be useful but for now we are not
implementing anything or planning anything on top of this so feel free to
ignore them.

**Comment by jack-oquin** [comment]
Since the scheduler does not "own" the uninvited clients, I will leave them out of the resource pool.

I suspect sharing resources between concerts will eventually involve some kind of higher-level scheduling to make them available.

**Comment by jack-oquin** [comment]
@stonier: I am still writing node-level rostests for the simple scheduler, but it should be functional for your testing, now. 

For that, you'll need to merge robotics-in-concert/rocon_msgs#81 and use the `platform_tuple_overhaul` branch of `rocon_scheduler_requests`.

The priority field in `scheduler_msgs/CurrentStatus` is not getting filled in yet.

**Comment by jack-oquin** [comment]
I'll be out of town the rest of this week, but can read e-mail intermittently. Let me know of any problems you encounter.

**Comment by jack-oquin** [comment]
With the new test case, I see that the scheduler is not publishing `/resource_pool` correctly.

I think it's fixed in f2283f3.

**Comment by stonier** [comment]
Thats ok Jack. I won't get a chance to look at this till early next week either. I had to abort and fix a module which was upgraded last sprint by another group, but carried hidden issues into the concert. Also got friends from Australia visiting :neckbeard:

**Comment by jack-oquin** [comment]
The simple_scheduler is passing its test cases, should be worth trying now.

**Comment by jack-oquin** [comment]
The priority is included in the `/resource_pool` topic, now.

**Comment by jack-oquin** [comment]
This is working now.
